use phf::phf_ordered_map;

/// This list represents the mapping between package name you install and the module name you
/// import.
///
/// Keys are PEP 503 normalized package names (lowercase, with runs of `-`,
/// `_`, and `.` collapsed to a single `-`); lookups normalize the declared
/// name the same way, so any spelling a user writes in pyproject.toml finds
/// its entry.
///
/// This is required because there is not always a programatic way to determine this mapping [[1]].
///
/// Some entries in the map also exploit the set of aliases we automatically
/// generate (e.g., databricks-sql), to improve the mapping.
///
/// If you would like to add or improve this list, please file a PR:
/// <https://github.com/lukehsiao/pyproject-udeps>.
///
/// Please try to keep this list sorted lexicographically and wrapped to 79
/// columns (inclusive).
///
/// [1]: https://stackoverflow.com/a/54853084
#[rustfmt::skip]
pub static KNOWN_NAMES: phf::OrderedMap<&str, &str> = phf_ordered_map! {
    "a2a-sdk" => "a2a",
    "absl-py" => "absl",
    "agent-client-protocol" => "acp",
    "amplitude-analytics" => "amplitude",
    "ansible" => "ansible_collections",
    "ansible-core" => "ansible",
    "ansicolors" => "colors",
    "antlr4-python3-runtime" => "antlr4",
    "apache-airflow" => "airflow",
    "apache-airflow-providers-cncf-kubernetes" =>
        "airflow-providers-cncf-kubernetes",
    "apache-airflow-providers-common-compat" =>
        "airflow-providers-common-compat",
    "apache-airflow-providers-common-io" => "airflow-providers-common-io",
    "apache-airflow-providers-common-sql" => "airflow-providers-common-sql",
    "apache-airflow-providers-databricks" => "airflow-providers-databricks",
    "apache-airflow-providers-fab" => "airflow-providers-fab",
    "apache-airflow-providers-ftp" => "airflow-providers-ftp",
    "apache-airflow-providers-google" => "airflow-providers-google",
    "apache-airflow-providers-http" => "airflow-providers-http",
    "apache-airflow-providers-imap" => "airflow-providers-imap",
    "apache-airflow-providers-mysql" => "airflow-providers-mysql",
    "apache-airflow-providers-slack" => "airflow-providers-slack",
    "apache-airflow-providers-smtp" => "airflow-providers-smtp",
    "apache-airflow-providers-snowflake" => "airflow-providers-snowflake",
    "apache-airflow-providers-sqlite" => "airflow-providers-sqlite",
    "apache-airflow-providers-ssh" => "airflow-providers-ssh",
    "argon2-cffi" => "argon2",
    "astronomer-cosmos" => "cosmos",
    "atlassian-python-api" => "atlassian",
    "aws-sam-translator" => "samtranslator",
    "azure-storage-file-datalake" => "azure-storage-filedatalake",
    "azure-storage-file-share" => "azure-storage-fileshare",
    "beautifulsoup4" => "bs4",
    "biopython" => "Bio",
    "boolean-py" => "boolean",
    "boto3-stubs" => "mypy_boto3_iam",
    "celery-redbeat" => "redbeat",
    "cfn-lint" => "cfnlint",
    "cyclonedx-python-lib" => "cyclonedx",
    "databricks-sdk" => "databricks.sdk",
    "databricks-sql-connector" => "databricks-sql",
    "datetime" => "DateTime",
    "dbt-core" => "dbt",
    "dbt-protos" => "dbtlabs",
    "delta-spark" => "delta",
    "django-cors-headers" => "corsheaders",
    "django-debug-toolbar" => "debug_toolbar",
    "django-filter" => "django_filters",
    "django-storages" => "storages",
    "django-stubs" => "mypy_django_plugin",
    "djangorestframework" => "rest_framework",
    "dnspython" => "dns",
    "docker-pycreds" => "dockerpycreds",
    "factory-boy" => "factory",
    "faiss-cpu" => "faiss",
    "faiss-gpu" => "faiss",
    "fastmcp-slim" => "fastmcp",
    "ffmpeg-python" => "ffmpeg",
    "fonttools" => "fontTools",
    "fpdf2" => "fpdf",
    "gitpython" => "git",
    "google-api-core" => "google-api_core",
    "google-api-python-client" => "googleapiclient",
    "google-cloud-appengine-logging" => "google-cloud-appengine_logging",
    "google-cloud-audit-log" => "google-cloud-audit",
    "google-cloud-bigquery-datatransfer" =>
        "google-cloud-bigquery_datatransfer",
    "google-cloud-bigquery-storage" => "google-cloud-bigquery_storage",
    "google-cloud-build" => "google-cloud-devtools",
    "google-cloud-dataflow-client" => "google-cloud-dataflow",
    "google-cloud-dataproc-metastore" => "google-cloud-metastore",
    "google-cloud-os-login" => "google-cloud-oslogin",
    "google-cloud-pubsub" => "google-cloud-pubsub_v1",
    "google-cloud-resource-manager" => "google-cloud-resourcemanager",
    "google-cloud-secret-manager" => "google-cloud-secretmanager",
    "google-cloud-storage-control" => "google-cloud-storage_control",
    "google-cloud-storage-transfer" => "google-cloud-storage_transfer",
    "google-pasta" => "pasta",
    "google-re2" => "re2",
    "google-resumable-media" => "google-resumable_media",
    "googleapis-common-protos" => "google-api",
    "graphql-core" => "graphql",
    "gremlinpython" => "gremlin_python",
    "griffelib" => "griffe",
    "grpc-google-iam-v1" => "google-iam-v1",
    "grpcio" => "grpc",
    "grpcio-gcp" => "grpc_gcp",
    "grpcio-health-checking" => "grpc_health",
    "grpcio-reflection" => "grpc_reflection",
    "grpcio-status" => "grpc_status",
    "grpcio-tools" => "grpc_tools",
    "hydra-colorlog" => "colorlog",
    "hydra-core" => "hydra",
    "imbalanced-learn" => "imblearn",
    "import-linter" => "importlinter",
    "impyla" => "impala",
    "inquirerpy" => "InquirerPy",
    "ipython" => "IPython",
    "jpype1" => "jpype",
    "json-stream" => "json_stream",
    "jsonpath-python" => "jsonpath",
    "jupyter" => "IPython",
    "kafka-python" => "kafka",
    "keyrings-google-artifactregistry-auth" => "google_artifactregistry_auth",
    "launchdarkly-eventsource" => "ld_eventsource",
    "launchdarkly-server-sdk" => "ldclient",
    "levenshtein" => "Levenshtein",
    "linkify-it-py" => "linkify_it",
    "llama-index-core" => "llama_index-core",
    "llama-index-indices-managed-llama-cloud" =>
        "llama_index-indices-managed-llama_cloud",
    "llama-index-llms-openai" => "llama_index-llms-openai",
    "llama-index-readers-llama-parse" => "llama_index-readers-llama_parse",
    "llama-index-workflows" => "workflows",
    "markdown-it-py" => "markdown_it",
    "meson" => "mesonbuild",
    "meson-python" => "mesonpy",
    "microsoft-kiota-abstractions" => "kiota_abstractions",
    "microsoft-kiota-authentication-azure" => "kiota_authentication_azure",
    "microsoft-kiota-http" => "kiota_http",
    "microsoft-kiota-serialization-json" => "kiota_serialization_json",
    "microsoft-kiota-serialization-text" => "kiota_serialization_text",
    "mini-swe-agent" => "minisweagent",
    "mkdocs-material" => "material",
    "mkdocs-material-extensions" => "materialx",
    "mkdocstrings-python" => "mkdocstrings_handlers",
    "mlflow-skinny" => "mlflow",
    "msoffcrypto-tool" => "msoffcrypto",
    "mysql-connector-python" => "mysql-connector",
    "mysqlclient" => "MySQLdb",
    "nexus-rpc" => "nexusrpc",
    "nodejs-wheel-binaries" => "nodejs_wheel",
    "nvidia-ml-py" => "pynvml",
    "office365-rest-python-client" => "office365",
    "openai-agents" => "agents",
    "opencensus-context" => "opencensus-common",
    "opencv-contrib-python" => "cv2",
    "opencv-python" => "cv2",
    "opencv-python-headless" => "cv2",
    "openlineage-python" => "openlineage",
    "opensearch-py" => "opensearchpy",
    "opentelemetry-api" => "opentelemetry",
    "opentelemetry-exporter-gcp-trace" => "opentelemetry-exporter-cloud_trace",
    "opentelemetry-instrumentation-aiohttp-client" =>
        "opentelemetry-instrumentation-aiohttp_client",
    "opentelemetry-instrumentation-system-metrics" =>
        "opentelemetry-instrumentation-system_metrics",
    "opentelemetry-propagator-aws-xray" => "opentelemetry-propagators-aws",
    "opentelemetry-resourcedetector-gcp" =>
        "opentelemetry-resourcedetector-gcp_resource_detector",
    "opentelemetry-semantic-conventions" => "opentelemetry-semconv",
    "opentelemetry-semantic-conventions-ai" => "opentelemetry-semconv_ai",
    "opentelemetry-test-utils" => "opentelemetry-test",
    "packageurl-python" => "packageurl",
    "pdfminer-six" => "pdfminer",
    "pillow" => "PIL",
    "pip-tools" => "piptools",
    "progressbar2" => "progressbar",
    "proto-plus" => "proto",
    "protobuf" => "google.protobuf",
    "psycopg2-binary" => "psycopg2",
    "py-cpuinfo" => "cpuinfo",
    "py-key-value-aio" => "key_value-aio",
    "py-key-value-shared" => "key_value-shared",
    "pyautogen" => "autogen",
    "pybars3" => "pybars",
    "pycryptodome" => "Crypto",
    "pycryptodomex" => "Cryptodome",
    "pydantic-ai-slim" => "pydantic_ai",
    "pydocket" => "docket",
    "pyelftools" => "elftools",
    "pygithub" => "github",
    "pyhcl" => "hcl",
    "pyinstaller" => "PyInstaller",
    "pyjwt" => "jwt",
    "pymdown-extensions" => "pymdownx",
    "pynacl" => "nacl",
    "pyopenssl" => "OpenSSL",
    "pypdf2" => "PyPDF2",
    "pyserial" => "serial",
    "pysocks" => "socks",
    "pyspnego" => "spnego",
    "pytest-json-ctrf" => "ctrf",
    "pytest-json-report" => "pytest_jsonreport",
    "pytest-runner" => "ptr",
    "pytest-xdist" => "xdist",
    "python-bidi" => "bidi",
    "python-crontab" => "crontab",
    "python-daemon" => "daemon",
    "python-dateutil" => "dateutil",
    "python-decouple" => "decouple",
    "python-docx" => "docx",
    "python-dotenv" => "dotenv",
    "python-engineio" => "engineio",
    "python-frontmatter" => "frontmatter",
    "python-gitlab" => "gitlab",
    "python-gnupg" => "gnupg",
    "python-hcl2" => "hcl2",
    "python-jose" => "jose",
    "python-json-logger" => "pythonjsonlogger",
    "python-levenshtein" => "Levenshtein",
    "python-magic" => "magic",
    "python-multipart" => "multipart",
    "python-pptx" => "pptx",
    "python-slugify" => "slugify",
    "python-snappy" => "snappy",
    "python-socketio" => "socketio",
    "python-telegram-bot" => "telegram",
    "python-ulid" => "ulid",
    "python3-saml" => "onelogin",
    "pytorch-nlp" => "torchnlp",
    "pyvespa" => "vespa",
    "pywavelets" => "pywt",
    "pywin32" => "pythoncom",
    "pywin32-ctypes" => "win32ctypes",
    "pyyaml" => "yaml",
    "pyyaml-env-tag" => "yaml_env_tag",
    "pyyaml-ft" => "yaml_ft",
    "pyzmq" => "zmq",
    "requirements-parser" => "requirements",
    "rpds-py" => "rpds",
    "scikit-image" => "skimage",
    "scikit-learn" => "sklearn",
    "segment-analytics-python" => "segment-analytics",
    "snowflake-connector-python" => "snowflake",
    "snowflake-snowpark-python" => "snowflake-snowpark",
    "speechrecognition" => "speech_recognition",
    "sseclient-py" => "sseclient",
    "std-uritemplate" => "stduritemplate",
    "strands-agents" => "strands",
    "uc-micro-py" => "uc_micro",
    "unicodedata2" => "unicodedata",
    "universal-pathlib" => "upath",
    "uuid7" => "uuid_extensions",
    "vcrpy" => "vcr",
    "vl-convert-python" => "vl_convert",
    "weaviate-client" => "weaviate",
    "websocket-client" => "websocket",
    "wikipedia-api" => "wikipediaapi",
};

#[cfg(test)]
mod tests {
    use super::KNOWN_NAMES;

    #[test]
    fn known_names_are_sorted() {
        let mut names = KNOWN_NAMES.entries().map(|(name, _alias)| name);

        let Some(mut previous_name) = names.next() else {
            return;
        };

        for name in names {
            assert!(
                name > previous_name,
                r#""{name}" should be sorted before "{previous_name}" in `KNOWN_NAMES`"#,
            );

            previous_name = name;
        }
    }
}
